<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vehicle extends Model
{
    use HasFactory;

    protected $table = 'vehicles';

    // Kolom-kolom yang boleh diisi
    protected $fillable = [
        'barcode',
        'barcodes',
        'vehicle_name',
        'tanggal_prediksi',
        'tindakan',
        'catatan',
        'vehicle_type',
        'klasifikasi_kendaraan',
        'vehicle_condition',
        'vol_tangki',
        'odo_meter',
        'tanggal_oli',
        'tanggal_aki',
        'oli_selanjutnya',
        'jenis_peralatan',
        'no_polisi',
        'tahun',
        'user_peralatan',
        'lokasi',
        'no_aset',
        'no_rangka',
        'no_mesin',
        'engine',
        'kap_silinder',
        'transmisi',
        'bakar_jenis',
        'bakar_kapasitas',
        'oli_mesin_volume1',
        'oli_mesin_jenis1',
        'oli_mesin_volume2',
        'oli_mesin_jenis2',
        'oli_transmisi_volume',
        'oli_transmisi_jenis',
        'oli_gardan_volume',
        'oli_gardan_jenis',
        'oli_hydrolis_volume',
        'oli_hydrolis_oli',
        'ban_depan',
        'ban_belakang',
        'ban_jumlah',
        'accu1_spesifikasi',
        'accu2_spesifikasi',
        'accu1_jumlah',
        'accu2_jumlah',
        'bagian',
        'oli_gardan',
        'oli_hidrolis',
        'filter_air_drayer',
        'filter_water_sparator',
        'filter_transmisi',
        'filter_hidrolis',
        'cooling_system',
        'airdrayer',
        'pneumatic_system',
        'hydraulic_system',
        'electrical_system',
        'kompresor',
        'folklamp',
        'retting_depan',
        'retting_belakang',
        'lampu_kompartement',
        'lampu_body',
        'ban_tengah_kanan',
        'ban_tengah_kiri',
        'pompa_fire_fighting',
        'primming_pump',
        'roof_turret',
        'bumper_turret',
        'undertrack_spray_depan',
        'undertrack_spray_kanan',
        'undertrack_spray_kiri',
        'foam_proportioner',
        'tangki_air',
        'tangki_foam',
        'pengisian_air_eksternal',
        'charger_baterai_eksternal',
        'top_speed',
        'stop_distance',
        'acceleration',
        'discharge_range',
        'discharge_rate',
        'foto_kendaraan',
        'tampil_dashboard',
        'tampil_cetak',
    ];
}
